config/routes.rb
Rails.application.routes.draw do

  # デバイス（Devise）に関連するルート
  devise_for :users

  # ルートパス（ホームページ）
  root 'rooms#index'

  get 'my_rooms', to: 'rooms#my_rooms'
  get 'rooms/search', to: 'rooms#search'
  
  # ログインせずにアクセス可能なページ
  resources :rooms, only: [:index, :show, :new] # GuestHouse一覧と詳細


  # ログインが必要なページ
  authenticate :user do
    # 予約関連のルート
    resources :reservations, only: [:new, :create, :edit, :update, :index, :destroy]
    get 'reservations/confirm', to: 'reservations#confirm', as: 'reservations_confirm'
    get 'reservations/edit_confirm', to: 'reservations#edit_confirm', as: 'edit_confirm_reservations'

  end

    # ユーザー関連のルート（Devise以外）
    resources :users, only: [] do
      member do
        get 'show_account_info'
        get 'edit_account_info'
        patch 'update_account_info'
        get 'edit_profile'
        patch 'update_profile'
        get 'show_profile'
      end
    end

    # 自分のGuestHouseに関連するルート
    resources :rooms, except: [:index, :show, :new]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms, dependent: :destroy
  #
  has_many :reservations, dependent: :destroy

  has_one_attached :icon_image

  private

  def icon_image_type
    if icon_image.attached? && !icon_image.content_type.in?(%('image/jpeg image/png'))
      errors.add(:icon_image, 'はJPEGまたはPNG形式でなければなりません。')
    end
  end

  def icon_image_size
    if icon_image.attached? && icon_image.blob.byte_size > 5.megabytes
      errors.add(:icon_image, 'のサイズは5MB以下でなければなりません。')
    end
  end

  # ユーザー登録時に名前の存在を確認する
  validates :email, presence: true
  validates :name, presence: true
  
  validates :introduction, length: { maximum: 500 }


  # プロフィールを更新する
  def update_profile(profile_params)
    self.update(profile_params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show_account_info, :edit_account_info, :update, :edit_profile, :update_profile]

  def show_account_info
    # ユーザーのアカウント情報を表示
  end

  def edit_account_info
    # ユーザー情報の編集ページ
  end

  def update
    # ユーザー情報の更新
    if @user.update(user_params)
      redirect_to show_account_info_user_path(@user)
    else
      render :edit_account_info
    end
  end

  def edit_profile
    # プロフィール編集ページ
  end

  def update_profile
    # プロフィール情報の更新
    if @user.update(profile_params)
      redirect_to show_profile_user_path(@user)
    else
      render :edit_profile
    end
  end

  def show_profile
    # プロフィール表示ページ
    @user = User.find(params[:id])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def profile_params
    params.require(:user).permit(:name, :icon_image, :introduction) 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_profile.html.erb
  <%= form_with(model: @user, url: update_profile_user_path(@user), local: true, multipart: true) do |form| %>
   <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>エラーが発生しました</h2> 

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.label :icon_image, 'プロフィール画像' %>
      <%= form.file_field :icon_image %>
    </div>

    <div class="field">
      <%= form.label :name, '名前' %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :introduction, '自己紹介' %>
      <%= form.text_area :introduction %>
    </div>

    <div class="actions">
      <%= form.submit "保存" %>
      <%= link_to 'キャンセル', show_profile_user_path(@user), class: 'btn btn-secondary' %>
    </div>
  <% end %>

app/views/users/show_account_info.html.erb
<%# app/views/users/show_account_info.html.erb %>

<div class="user-account-info">
  <h2>アカウント情報</h2>

  <p><strong>メールアドレス：</strong><%= @user.email %></p>
  <p><strong>パスワード：</strong>********</p>

  <%= link_to 'プロフィール表示', show_profile_user_path(@user), class: 'btn btn-secondary' %>
  <%= link_to 'アカウント設定を編集', edit_user_registration_path, class: 'btn btn-secondary' %>


</div>

app/views/users/show_profile.html.erb
<%# app/views/users/show_profile.html.erb %>

<div class="user-profile">
  <div class="user-profile-item">
    <strong>アイコン画像：</strong>
    <% if @user.icon_image.attached? %>
      <%= image_tag @user.icon_image, class: "user-icon" %>
    <% else %>
      <p>No image available</p>
    <% end %>
  </div>

  <div class="user-profile-item">
    <strong>名前：</strong>
    <p><%= @user.name %></p>
  </div>

  <div class="user-profile-item">
    <strong>自己紹介：</strong>
    <% if @user.introduction.present? %>
      <p><%= @user.introduction %></p>
    <% else %>
      <p>No introduction provided.</p>
    <% end %>
  </div>

  <%= link_to 'プロフィール編集', edit_profile_user_path(@user), class: 'btn btn-secondary' %>
  <%= link_to 'アカウント情報表示', show_account_info_user_path(@user), class: 'btn btn-secondary' %>
</div>