config/routes.rb
Rails.application.routes.draw do

  # デバイス（Devise）に関連するルート
  devise_for :users

  # ルートパス（ホームページ）
  root 'rooms#index'

  get 'my_rooms', to: 'rooms#my_rooms'
  get 'rooms/search', to: 'rooms#search'
  
  # ログインせずにアクセス可能なページ
  resources :rooms, only: [:index, :show, :new] # GuestHouse一覧と詳細


  # ログインが必要なページ
  authenticate :user do
    # 予約関連のルート
    resources :reservations, only: [:new, :create, :edit, :update, :index, :destroy]
    get 'reservations/confirm', to: 'reservations#confirm', as: 'reservations_confirm'
    get 'reservations/edit_confirm', to: 'reservations#edit_confirm', as: 'edit_confirm_reservations'

  end

    # ユーザー関連のルート（Devise以外）
    resources :users, only: [] do
      member do
        get 'show_account_info'
        get 'edit_account_info'
        patch 'update_account_info'
        get 'edit_profile'
        patch 'update_profile'
        get 'show_profile'
      end
    end

    # 自分のGuestHouseに関連するルート
    resources :rooms, except: [:index, :show, :new]
  
end

app/views/shared/_header.html.erb
<div class="partial">
<%# app/views/shared/_header.html.erb %>
 
  <div class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to 'Guest House App', rooms_path, class: "nav-link" %>
    <% if user_signed_in? %>
      <div class="nav-item dropdown">
      <% if current_user.icon_image.attached? %>
        <%= image_tag current_user.icon_image, class: "user-icon" %>
      <% end %>
        <%= link_to '#', class: "nav-link dropdown-toggle", role: "button", id: "navbarDropdown", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } do %>
          <%= current_user.name %>
        <% end %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to '新規部屋登録', new_room_path, class: "dropdown-item" %>
          <%= link_to '登録した部屋', my_rooms_path, class: "dropdown-item" %>
          <%= link_to '予約一覧', reservations_path, class: "dropdown-item" %> 
          <%= link_to 'プロフィール', show_profile_user_path(current_user), class: "dropdown-item" %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <div class="auth-links">
        <%= link_to 'ログイン', new_user_session_path, class: "nav-link-auth" %>
        <%= link_to '新規登録', new_user_registration_path, class: "nav-link-auth" %>
      </div>
     <% end %>
  </div>
</div>