config/routes.rb
Rails.application.routes.draw do

  # デバイス（Devise）に関連するルート
  devise_for :users

  # ルートパス（ホームページ）
  root 'rooms#index'

  get 'my_rooms', to: 'rooms#my_rooms'
  get 'rooms/search', to: 'rooms#search'
  
  # ログインせずにアクセス可能なページ
  resources :rooms, only: [:index, :show, :new] # GuestHouse一覧と詳細


  # ログインが必要なページ
  authenticate :user do
    # 予約関連のルート
    resources :reservations, only: [:new, :create, :edit, :update, :index, :destroy]
    get 'reservations/confirm', to: 'reservations#confirm', as: 'reservations_confirm'
    get 'reservations/edit_confirm', to: 'reservations#edit_confirm', as: 'edit_confirm_reservations'

  end

    # ユーザー関連のルート（Devise以外）
    resources :users, only: [] do
      member do
        get 'show_account_info'
        get 'edit_account_info'
        patch 'update_account_info'
        get 'edit_profile'
        patch 'update_profile'
        get 'show_profile'
      end
    end

    # 自分のGuestHouseに関連するルート
    resources :rooms, except: [:index, :show, :new]
  
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :check_in_date, presence: true
  validates :check_out_date, presence: true
  validates :number_of_people, presence: true, numericality: { greater_than_or_equal_to: 1 }

  validate :check_in_date_cannot_be_in_the_past
  validate :check_out_date_must_be_after_check_in_date

  private

  def check_in_date_cannot_be_in_the_past
    errors.add(:check_in_date, "は本日以降の日付にしてね！！！") if check_in_date.present? && check_in_date < Date.today
  end

  def check_out_date_must_be_after_check_in_date
    if check_out_date.present? && check_in_date.present? && check_out_date <= check_in_date
      errors.add(:check_out_date, "はチェックイン日よりも後の日付にしてね！！！")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, only: [:edit, :update, :destroy]
  before_action :set_room, only: [:confirm]

  def index
    @reservations = current_user.reservations
  end

  def new
    @reservation = Reservation.new
  end
  
  def create
    # @reservation = @room.reservations.new(reservation_params)
    # @reservation.user = current_user
    puts "####MAKING RESERVATION!!!!" 
    puts reservation_params
    @room = Room.find(params[:reservation][:room_id])

    @reservation = current_user.reservations.new(reservation_params)
    @reservation.total_price = calculate_total_price(@reservation)

    if @reservation.save
      redirect_to reservations_path
    else
      redirect_to room_path(@reservation.room), alert: '予約に失敗しました。'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end
  
  #予約編集ページを表示
  def edit
    @reservation = current_user.reservations.find(params[:id])
    @room = @reservation.room
  end
  
  #予約編集確認
  def edit_confirm
    @reservation = current_user.reservations.find(params[:reservation][:id])
    @reservation.assign_attributes(reservation_params) # 編集内容を仮に割り当てる
  
    if @reservation.valid? # 検証を行う
      @room = Room.find(@reservation.room_id)
      @total_price = calculate_total_price(@reservation)
      render :edit_confirm
    else
      @room = @reservation.room
      render :edit # エラーがあれば編集画面に戻る
    end
  end

 #予約編集確定
  def update
    @reservation = current_user.reservations.find(params[:id])
    @room = @reservation.room 

    if @reservation.update(reservation_params)
      @reservation.total_price = calculate_total_price(@reservation)
      @reservation.save
      redirect_to reservations_path
    else
      render :edit
    end
  end

  def confirm
    @reservation = Reservation.new(confirm_params)
    @room = Room.find(params[:reservation][:room_id])
    @reservation.user = current_user  # 現在のユーザーを予約に関連付ける

  
    if @reservation.valid?
      @total_price = calculate_total_price(@reservation)
      render :show
    else
      render 'rooms/show'
    end
  end
  
  
  
  

  def destroy
    puts "DELETING NOW"
    @reservation.destroy
    redirect_to reservations_path
    #@reservation = Reservation.find(params[:id])
    #if @reservation.destroy
      #puts "DELETED !!!"
    #end
  end

  private
  
  def calculate_total_price(reservation)
    # 支払い金額の計算
    (reservation.check_out_date - reservation.check_in_date).to_i * reservation.number_of_people * @room.price
  end

  def set_reservation
    @reservation = current_user.reservations.find(params[:id])
  end

  def set_room
    room_id = params[:reservation][:room_id]
    @room = Room.find(room_id)
  end

  def reservation_params
    params.require(:reservation).permit(:room_id, :check_in_date, :check_out_date, :number_of_people)
  end
  
  def confirm_params
    params.require(:reservation).permit(:room_id, :check_in_date, :check_out_date, :number_of_people)
  end


end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/edit.html.erb
<%# app/views/reservations/edit.html.erb %>
<h1>予約内容の編集</h1>
<% if @reservation.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @reservation.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="reservation-details">
  <% if @room.image.attached? %>
    <div class="room-image">
      <%= image_tag @room.image %>
    </div>
  <% else %>
    <p>画像はありません。</p>
  <% end %>
  <p>部屋名: <%= @room.name %></p>
  <p>Address: <%= @room.address %></p>
  <p>Price: <%= @room.price %>円</p>

</div>

<%= form_with model: @reservation, url: edit_confirm_reservations_path, method: :get, local: true do |form| %>


  <%= form.hidden_field :id %>

  <div class="form-group">
    <%= form.label :check_in_date, "チェックイン日" %>
    <%= form.date_field :check_in_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :check_out_date, "チェックアウト日" %>
    <%= form.date_field :check_out_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :number_of_people, "宿泊人数" %>
    <%= form.number_field :number_of_people, class: "form-control" %>
  </div>

  <%= form.submit "変更内容を確認", class: "btn btn-primary" %>
<% end %>

app/views/reservations/edit_confirm.html.erb
<%# app/views/reservations/edit_confirm.html.erb %>
<h1>予約内容の確認</h1>

<div class="reservation-details">
  <% if @room.image.attached? %>
    <div class="room-image">
      <%= image_tag @room.image %>
    </div>
  <% else %>
    <p>画像はありません。</p>
  <% end %>
  <p>部屋名: <%= @room.name %></p>
  <p>Address: <%= @room.address %></p>
  <p>Price: <%= @room.price %>円</p>
</div>

<div class="reservation-details">
  <!-- 確認内容の表示 -->
  <p>チェックイン日: <%= @reservation.check_in_date %></p>
  <p>チェックアウト日: <%= @reservation.check_out_date %></p>
  <p>宿泊人数: <%= @reservation.number_of_people %></p>
  <p>合計料金: <%= @total_price %>円</p>
</div>

<%= form_with model: @reservation, url: reservation_path(@reservation), method: :patch, local: true do |form| %>
  <%= form.hidden_field :check_in_date, value: @reservation.check_in_date %>
  <%= form.hidden_field :check_out_date, value: @reservation.check_out_date %>
  <%= form.hidden_field :number_of_people, value: @reservation.number_of_people %>

  <%= form.submit "予約内容の変更を確定", class: "btn btn-primary" %>
<% end %>


<%= link_to '編集に戻る', edit_reservation_path(@reservation), class: "btn btn-secondary" %>

app/views/reservations/index.html.erb
<h1>予約一覧</h1>

<% @reservations.each do |reservation| %>
  <div class="reservation">
    <div class="reservation-image">
      <%= image_tag reservation.room.image if reservation.room.image.attached? %>
    </div>
    <div class="reservation-details">
      <h3><%= link_to reservation.room.name, room_path(reservation.room) %></h3>
      <p><%= reservation.room.description %></p>
      <p>合計料金: <%= reservation.total_price %>円</p>
      <p>チェックイン日: <%= reservation.check_in_date %></p>
      <p>チェックアウト日: <%= reservation.check_out_date %></p>
      <p>予約確定日時: <%= reservation.created_at.strftime("%Y-%m-%d %H:%M") %></p>
    </div>

    <!-- ドロップダウンメニュー -->
 <div class="dropdown">
      <%= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do %>
        オプション
      <% end %>
      <div class="dropdown-menu">
        <%= link_to '編集', edit_reservation_path(reservation), class: 'dropdown-item' %>
        <%= link_to 'キャンセル', reservation_path(reservation), method: :delete, data: { confirm: '本当にキャンセルしますか？' }, class: 'dropdown-item' %>
      </div>
    </div>
  </div>
<% end %>

app/views/reservations/show.html.erb
<%# app/views/reservations/show.html.erb %>

<h1>予約内容の確認</h1>

<div class="reservation-details">
  <% if @room.image.attached? %>
    <div class="room-image">
      <%= image_tag @room.image %>
    </div>
  <% else %>
    <p>画像はありません。</p>
  <% end %>
  <p>ゲストハウス名: <%= @room.name %></p>
  <p>チェックイン日: <%= @reservation.check_in_date %></p>
  <p>チェックアウト日: <%= @reservation.check_out_date %></p>
  <p>宿泊日数: <%= (@reservation.check_out_date - @reservation.check_in_date).to_i %>日</p>
  <p>人数: <%= @reservation.number_of_people %>人</p>
  <p>合計料金: <%= @total_price %>円</p>
</div>

<!-- 予約確定フォーム -->
<%= form_with model: @reservation, url: reservations_path, method: :post, local: true do |form| %>
  <%= form.hidden_field :check_in_date %>
  <%= form.hidden_field :check_out_date %>
  <%= form.hidden_field :number_of_people %>
  <%= form.hidden_field :room_id, value: @room.id %>
  
  <%= form.submit "予約を確定する", class: "btn btn-primary" %>
<% end %>

<!-- キャンセル（部屋の詳細ページに戻る） -->
<%= link_to 'キャンセル', room_path(@room), class: "btn btn-secondary" %>