config/routes.rb
Rails.application.routes.draw do

  # デバイス（Devise）に関連するルート
  devise_for :users

  # ルートパス（ホームページ）
  root 'rooms#index'

  get 'my_rooms', to: 'rooms#my_rooms'
  get 'rooms/search', to: 'rooms#search'
  
  # ログインせずにアクセス可能なページ
  resources :rooms, only: [:index, :show, :new] # GuestHouse一覧と詳細


  # ログインが必要なページ
  authenticate :user do
    # 予約関連のルート
    resources :reservations, only: [:new, :create, :edit, :update, :index, :destroy]
    get 'reservations/confirm', to: 'reservations#confirm', as: 'reservations_confirm'
    get 'reservations/edit_confirm', to: 'reservations#edit_confirm', as: 'edit_confirm_reservations'

  end

    # ユーザー関連のルート（Devise以外）
    resources :users, only: [] do
      member do
        get 'show_account_info'
        get 'edit_account_info'
        patch 'update_account_info'
        get 'edit_profile'
        patch 'update_profile'
        get 'show_profile'
      end
    end

    # 自分のGuestHouseに関連するルート
    resources :rooms, except: [:index, :show, :new]
  
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy

  has_one_attached :image
  
  validates :name, :description, :price, :address, presence: true
  # 料金は1円以上でなければならない
  validates :price, numericality: { greater_than_or_equal_to: 1 }

  # Active Storageを使用、画像一つ追加
  has_one_attached :image

  # 施設作成日をyyyy/mm/ddの形式で表示する
  def formatted_creation_date
    created_at.strftime('%Y/%m/%d')
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :set_room, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
  
    def index
      @rooms = Room.all
  
      if params[:area].present?
        @rooms = @rooms.where('address LIKE ?', "%#{params[:area]}%")
      end
  
      if params[:keyword].present?
        @rooms = @rooms.where('name LIKE :keyword OR description LIKE :keyword', keyword: "%#{params[:keyword]}%")
      end
    end


    def show
      print "部屋詳細"
    end
    
    def my_rooms
      @rooms = current_user.rooms
    end
  
    def new
      # 新規部屋登録フォーム
      @room = Room.new
    end
  
    def create
      @room = current_user.rooms.new(room_params)
      if @room.save
        redirect_to @room
      else
        render :new
      end
    end
  
    def edit
      # 部屋の編集フォーム
    end
  
    def update
      # 部屋の更新処理
      if @room.update(room_params)
        redirect_to @room
      else
        render :edit
      end
    end
  
    def destroy
      # 部屋の削除処理
      @room = Room.find(params[:id])
      @room.destroy
      redirect_to rooms_url
    end
  
    private

    def set_room
      @room = Room.find(params[:id])
    end
  
    def room_params
      params.require(:room).permit(:name, :description, :price, :address, :image)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<%# app/views/rooms/edit.html.erb %>
<h1>ゲストハウスの編集</h1>

<%= form_with(model: @room, local: true, url: room_path(@room), method: :patch) do |form| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2>エラーが発生しました:</h2>

      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ゲストハウス名 %>
    <%= form.text_field :name, id: :room_name %>
  </div>

  <div class="field">
    <%= form.label :説明 %>
    <%= form.text_area :description, id: :room_description %>
  </div>

  <div class="field">
    <%= form.label :１日あたりの料金 %>
    <%= form.number_field :price, id: :room_price %>
  </div>

  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :address, id: :room_address %>
  </div>

  <div class="field">
    <%= form.label :画像 %>
    <%= form.file_field :画像, id: :room_image %>
  </div>

  <div class="actions">
    <%= form.submit "変更を保存" %>
    <%= link_to 'キャンセル', my_rooms_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/rooms/index.html.erb
<%# /rooms%>
<div class="container">   
  
  <%= form_with(url: rooms_path, method: :get, local: true) do |form| %>
  <%= form.label :area, "エリアで検索" %>
  <%= form.select :area, ['東京', '大阪', '京都', '札幌'], prompt: "Select an area" %>

  <%= form.label :keyword, "キーワードで検索" %>
  <%= form.text_field :keyword, placeholder: "Enter facility name or details" %>

  <%= form.submit "Search" %>
<% end %>

  <h2>Guest Houses</h2>
  <p>ゲストハウスの数: <%= @rooms.count %></p>

  <% @rooms.each do |room| %>
    <div class="room">
      <h3><%= link_to room.name, room_path(room) %></h3>
      <p><%= room.description %></p>
      <p>料金/日: <%= room.price %>円</p>
      <p>住所: <%= room.address %></p>

      <% if room.image.attached? %>
        <%= image_tag room.image, class: "room-image" %>
      <% else %>
        <p>No image available</p>
      <% end %>
      <%= link_to '詳細', room_path(room), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/rooms/my_rooms.html.erb
<%# 自分の登録した部屋一覧/my_rooms.html.erb %>
<h1>My Guest House</h1>

<% if @rooms.any? %>
  <div class="rooms">
    <% @rooms.each do |room| %>
      <div class="room">
        <div class="room-info">
          <div class="room-text">
            <h2><%= link_to room.name, room_path(room) %></h2>
            <p><%= room.description %></p>
            <p>料金/日: <%= room.price %>円</p>
            <p>住所: <%= room.address %></p>
            <p>作成日: <%= room.created_at.strftime("%Y-%m-%d") %></p>

          </div>
          <div class="room-image">
            <% if room.image.attached? %>
              <%= image_tag room.image %>
            <% else %>
              <p>No image available</p>
            <% end %>
          </div>
          <div class="dropdown">
            <button class="dropbtn">オプション</button>
            <div class="dropdown-content">
              <%= link_to '詳細', room_path(room) %>
              <%= link_to '編集', edit_room_path(room) %>
              <%= link_to '登録削除', room, method: :delete, data: { confirm: '本当に登録を削除しますか？' } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>登録した部屋はまだありません</p>
<% end %>

app/views/rooms/new.html.erb
<!DOCTYPE html>
  <html>
   <div class="center-container">

    <h1>新規ゲストハウス登録</h1>

    <%= form_with(model: @room, local: true) do |form| %>
      <% if @room.errors.any? %>
        <div id="error_explanation">
          <h2>エラーが発生しました:</h2>
          <ul>
            <% @room.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name, "ゲストハウス名" %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :description, "詳細" %>
        <%= form.text_area :description %>
      </div>

      <div class="field">
        <%= form.label :price, "1日あたりの料金" %>
        <%= form.number_field :price %>
      </div>

      <div class="field">
        <%= form.label :address, "都道府県" %>
        <%= form.text_field :address %>
      </div>

      <div class="field">
        <%= form.label :image, "画像" %>
        <%= form.file_field :image %>
      </div>

      <div class="actions">
        <%= form.submit "登録する" %>
      </div>
    <% end %>
   </div>
  </html>

app/views/rooms/show.html.erb
<%# app/views/rooms/show.html.erb %>
<h1>ゲストハウスの詳細</h1>
<!-- エラーメッセージ表示 -->
<% if @reservation&.errors&.any? %>
  <div id="error_explanation">
    <ul>
      <% @reservation.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="room-details">
  <p><strong>ゲストハウス名:</strong> <%= @room.name %></p>
  <p><strong>詳細:</strong> <%= @room.description %></p>
  <p><strong>1日あたりの料金:</strong> <%= @room.price %>円</p>
  <p><strong>住所:</strong> <%= @room.address %></p>

  <% if @room.image.attached? %>
    <div class="room-image">
      <%= image_tag @room.image %>
    </div>
  <% else %>
    <p>画像はありません。</p>
  <% end %>
</div>



<%= form_with url: reservations_confirm_path, method: :get, local: true do |form| %>
  <%= form.hidden_field :room_id, value: @room.id, name: 'reservation[room_id]' %>

  <div class="form-group">
    <%= form.label :check_in_date, "チェックイン日" %>
    <%= form.date_field :check_in_date, class: "form-control", name: 'reservation[check_in_date]' %>
  </div>

  <div class="form-group">
    <%= form.label :check_out_date, "チェックアウト日" %>
    <%= form.date_field :check_out_date, class: "form-control", name: 'reservation[check_out_date]' %>
  </div>

  <div class="form-group">
    <%= form.label :number_of_people, "宿泊人数" %>
    <%= form.number_field :number_of_people, class: "form-control", name: 'reservation[number_of_people]' %>
  </div>

  <%= form.submit "予約内容を確認", class: "btn btn-primary" %>
<% end %>



<%= link_to '一覧に戻る', rooms_path %>